### ISSUE TITLE
mr_in function / in operator for multiple_response

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#102]
We're currently the following workaround for logical expressions against `multiple_response` variables:

```python
def mr_in(ds, mr_alias, subvars):
    """
    Temporary helper until scrunch can parse correctly the expression:
     mr.has_any([sv1, sv2...])
    """
    variables = ds.resource.variables.by('alias')
    mr = variables[mr_alias].entity
    subvariables = mr.subvariables.by('alias')
    return {
        'function': 'any',
        'args': [
            {'variable': mr.self},
            {
                'column': [
                    subvariables[scrunch.datasets.subvar_alias(mr_alias, sv)].id
                    for sv in subvars]}]}
```

This lets us write a `case` for a `multiple_response` in the following way:

```python
'case': mr_in(ds, 'WQP_q5d', [8, 9, 10, 11, 15])
```

Compare that to a regular `categorical` `case` which would be written:

```python
'case': 'WQP_q5d in [8, 9, 10, 11, 15]')
```

The primary goal is still to allow the same expression syntax for both `categorical` and `multiple_response` but if that is still a long way off, can we add the `mr_in` function to `scrunch.helpers.py`?

If `mr_in` was added to scrunch then would it be possible for the expression evaluation for `multiple_response` to internally end up there, rendering the use of `mr_in` invisible to users?

More complex expressions for dealing with `multiple_response` variables will be needed soon enough so tackling this more completely may be the better option.

**Comment by jamesrkg** [comment]
@xbito Just to add to this, there are additional use cases that we need to cater for which may prompt you to aim for a fully integrated solution rather than a work-around. Depending on how you want to tackle these we may need to just close this issue and open another one that is more appropriate for the solution you'll be implementing.

* We need to be able to combine references to more than just a single `multiple_response`, which isn't possible using `mr_in()`. For example: `q1 in [1, 2, 3] and q2 == 5` where `q1` is a `multiple_response` and `q2` is a `categorical` or a `numeric` (or `text` or `datetime`, etc.).
* We need to be able to negate a condition, such as `not q1 in [1, 2, 3]` where `q1` is a `multiple_response`, which isn't possible using `mr_in()`. Adding a second helper `not_mr_in()` is possible of course but that won't help us combine conditions, as described above.

**Comment by xbito** [comment]
@jamesrkg what's the normal syntax for this? is it "any (WQP_q5d_8, WQP_q5d_9, WQP_q5d_10, WQP_q5d_11,  WQP_q5d_15)"? or you don't have a way to express this at all?

**Comment by jamesrkg** [comment]
@xbito currently you'd need to check each subvaraible for `selected` like this:

`'WQP_q5d_8 == 1 or WQP_q5d_9 == 1 or WQP_q5d_10 == 1 or WQP_q5d_11 == 1 or WQP_q5d_15 == 1'`

What we want is to be able to simply write:

`WQP_q5d.any([8, 9, 10, 11, 15])`

**Comment by xbito** [comment]
See in a multiple that makes sense only for the case where you have 2 categories for each subvariable and one means selected (true) and the other not selected (false). The thing is Crunch multiple variable type is not geared towards that. I would find weird that scrunch supports a use case like that specially crafted for one kind of multiple variables.

I will continue the conversation with Jj, we have chatted about this before though we didn't reach a conclusion it is time to make a decision on how best to support this, or at least give a better interface for scrunch users.

**Comment by jjdelc** [comment]
We do have support for `any` functions on the Crunch API as the above implementation of `mr_in` shows. 

The situation here is that typing `any()` in scrunch does not parse correctly because it needs to distinguish the variable type if it is MR to then match the subvariables by alias and not the categories.

**Comment by jamesrkg** [comment]
@xbito in the scheme of things the exact implementation of multies in Crunch is arbitrary since you're right, `selected` could just as easily be `2` as it could be `1` or any other number, but the user experience of being able to simplify it down to `any([8, 9, 10, 11, 15])` is not arbitrary. For someone who only wants to know if they selected responses 8, 9, 10, 11 or 15 that is the most intuitive way of writing it.

Perhaps scrunch can determine if the 'named' subvariables data (unavoidably parsed by convention unless subvariables expressed an `id`-like attribute) contains any subvariable category for which `selected` is `True` to bring it back to an non-arbitrary Crunch way of interpreting this.

Something tells me getting at that would be a can of worms but it would allow us to avoid assuming `1 == selected` on faith.

**Comment by jjdelc** [comment]
We do have support for `any` functions on the Crunch API as the above implementation of `mr_in` shows. 

The situation here is that typing `any()` in scrunch does not parse correctly because it needs to distinguish the variable type if it is MR to then match the subvariables by alias and not the categories.

**Comment by jjdelc** [comment]
Right now MR variables created via scrunch have a convention in the alias that assumes the parent alias and the _id_ that the user defined as a suffix:
https://github.com/Crunch-io/scrunch/blob/master/scrunch/datasets.py#L1460

If you were to indicate `mymr in any([1, 2, 3])` it should be equivalent to `mymr in any([mymr_1, mymr_2, mymr_3])` which is simple to parse.

**Comment by xbito** [comment]
I know you really want to use categorical syntax for a multiple variable. I don't see that as possible, unless as you mentioned we start assuming things, like, it is a multiple that has only selected/not selected categories, and that selected is 1 and not selected 2. 

But looking at Jj last comment he seems to be proposing making `mymr in any([1, 2, 3])` the equivalent to `categorical in [1, 2, 3]`, it is not the same, but that expression could allow you to negate it and concat it with others. Is that acceptable? That syntax would also mean that `mymr in all([1, 2, 3])` would be acceptable.

**Comment by xbito** [comment]
Wishes granted! After a conversation with Jj I was educated, the multiple type does allow a selected parameter to signify the dichotomous property of the variable (selected/not selected). So they have the tools to interpret the query correctly without us passing the values we are seeking.

So, we should translate `mr_alias == [1, 2, 3]` to something like `{function: all, args: [ {variable: mr_url}, {column: [subvar_urls_list]} ]}` and `mr_alias in [1, 2, 3]` to something like {function: any, args: [ {variable: mr_url}, {column: [subvar_urls_list]} ]} taking into consideration that since we know how the subvariables aliases are built we can infer that 1, 2, 3 will correspond to mr_alias_1, mr_alias_2, mr_alias_3 and from there we can find out their URLs.

Obviously we also need to support the negative of those expressions so:
`mr_alias == [1, 2, 3]` and `mr_alias not in [1, 2, 3]` should translate to those same expressions about wrapped around a not crunch function.

**Comment by mathiasbc** [comment]
The syntax for this is what @jamesrkg proposed. `mr_alias.any([1,2,3])`. That way we keep the expression parser agnostic of the variable type, otherwise we would have to add the context of the variable to the expression parser to yield different structures.

The PR for this: 
https://github.com/Crunch-io/scrunch/pull/121
