### ISSUE TITLE
Appending

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#151]
While we clarify if we are going to do a new library or a separate module/class to do appends we should start working on the code here at least. Let's do appends and also compares.

We should look into the possible difficulties on appends with primary keys, checking what is done in the R library  (If I remember correctly there was something done to primary keys so that appends behave as appends, nor as an upsert).

**Comment by mathiasbc** [comment]
What exactly is an append and a compare ? I suppose appends are means of importing data into a Crunch dataset.

**Comment by xbito** [comment]
https://github.com/Crunch-io/rcrunch/blob/master/R/append-dataset.R
https://github.com/Crunch-io/rcrunch/blob/master/R/compare-datasets.R

**Comment by xbito** [comment]
Unsetting PK here: https://github.com/Crunch-io/rcrunch/blob/master/R/append-dataset.R#L37

**Comment by jjdelc** [comment]
We should not do a separate library but we should implement it as different subclasses of a same BaseDataset class.

We should implement the StreamingDataset and MutableDataset classes, both inheriting from BaseDataset class.

All of our current Dataset methods would go either to BaseDataset or StreamingDataset. MutableDataset would implement methods that allow for schema changing operations.

All of our decks, filters, multitables, analysis, export operations should be made to take both subclasses and operate the same since they are oblivious to the streaming state of the dataset.

This is a great oportunity to rethink the way we develop the operations around a Dataset so we move away from the Dataset class being a bag with hundreds of every method possible and segregate the operations in other helper classes/functions.

We provide a /compare/ endpoint in the API that will simulate an append between two datasets and return the errors or success without really performing an append.

**Comment by mathiasbc** [comment]
@jjdelc: Sounds good, I already implemented a compare that is a work in progress: https://github.com/Crunch-io/scrunch/blob/feature/material-joins/scrunch/append.py. I tried using the /compare endpoint but I only received 500 errors from Crunch. I asked Malecki on Slack but did not receive an answer. The documentation describes a GET with the appendable dataset url as a query parameter, are you sure this is a working feature ?

**Comment by xbito** [comment]
I see there are now docs for another endpoint "align" https://github.com/Crunch-io/apidocs/pull/133/files which might be useful for this too.

I also see that there is a new "combination" feature, do we want to bring that over to scrunch too? https://github.com/Crunch-io/apidocs/pull/131/files

**Comment by jjdelc** [comment]
@mathiasbc the idea of having different subclasses is to make it very explicit to users that they are dealing with different kind of things. Following the rationale of having two separate libraries to prevent users confusing one with the other.

Having two different classes and getter methods will raise alerts to the user quickly if they try to do the incorrect thing with the instance they have. We would want to split `get_dataset` in two functions, one for mutable and one for streaming datasets and raise an error if they try to fetch the wrong dataset on the wrong getter function. If we just gave them a dataset with the inherited class depending on the state the user wouldn't know that they are dealing with a streamed dataset or not unless they start inspecting their class and we want to avoid that, specially in scripts. Users should know before hand what they want to do with the dataset and get the necessary instance.

**Comment by mathiasbc** [comment]
@jjdelc: I see; and API-wise what's the way to differentiate between a Streaming Dataset and a Mutable Dataset ? What is your thinking about this @jamesrkg ?

**Comment by mathiasbc** [comment]
Pointed to it: https://github.com/Crunch-io/apidocs/pull/122/files. I will work on this then. Sorry for the confusing branch name, I make the wrong commit on the branch and just kept adding things.

**Comment by jamesrkg** [comment]
@mathiasbc assuming there's a dataset property `streaming` which is `True`/`False` that should be enough to work around any hurdles. I believe @jjdelc said this is already planned for on the Crunch side.

**Comment by mathiasbc** [comment]
This was merged already
