### ISSUE TITLE
Add a variable with data

### ISSUE THREAD

**Issue by xbito** [Crunch-io/scrunch#159]
One common use case so far is to create a new dataset with 1 or 2 columns and then perform a join between the two to bring over an extra column to the original dataset to perform a weight. But the whole process of creating a new dataset could be avoided if we are able to create a new variable and in the same step provide data for it, per this comment that should be possible:

https://github.com/Crunch-io/scrunch/issues/149#issuecomment-321368261

As far as I understand this process accepts only the column to be filled, so the user must know the exact order the dataset is in at the moment in Crunch in order to provide the data in that order.

**Comment by jamesrkg** [comment]
@xbito can we bump this one please? Can we also expand it to provide the ability to update the data for an existing variable (rather than only be able to import a column of data for a new variable)?

This would let us export data to pandas, make an ad hoc edits that were required there, then import the edited data either to overwrite an existing column/variable or to add a new column/variable.

**Comment by xbito** [comment]
Docs for adding a variable with data through the crunch api are here: http://docs.crunch.io/#2-add-variable-definitions-and-column-data

@mathiasbc can you propose a syntax for this?

**Comment by mathiasbc** [comment]
I see that the first step is providing an API for creating variables: http://docs.crunch.io/#variable-definitions. we only allow variable derivation at the moment.

**Comment by xbito** [comment]
That's correct @mathiasbc lets propose an API for that too.
