### ISSUE TITLE
(non-derived) Bind categorical variables into a categorical_array

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#182]
We've discussed this here: https://github.com/Crunch-io/scrunch/issues/113 but since it looks like the implementation needed will differ for derived variables versus non-derived variables, can we just get a version working for non-derived variables?

We can always use https://github.com/Crunch-io/scrunch/pull/158 to integrate and then bind derived variables if needed once this is put in place.

**Comment by mathiasbc** [comment]
@jjdelc: Following what I found on the docs and what I could infer from #113. I am trying to create a categorical_array from existing non-derived variables with the following payload being sent to the /variables endpoint:

```python
{ 
    "element": "shoji:entity",
    "body" : {
        "name": "test_create_cat_array",
        "alias": "test_create_cat_array",
    "description": "",
    "notes": "",
    "derivation": {
        "function": "array",
        "args": [
            {
                "function": "select",
                "args": [
                    {
                        "map": {
                            "00001": {
                                "variable": "https://alpha.crunch.io/api/datasets/9825ab3f23f4460288f6f74b6512f3e2/variables/000016/"
                            },
                            "00002": {
                                "variable": "https://alpha.crunch.io/api/datasets/9825ab3f23f4460288f6f74b6512f3e2/variables/000018/"
                            }
                        }
                    }
                ]
            }
        ]
    }
    }
}

**Comment by mathiasbc** [comment]
Also, following http://docs.crunch.io/#categorical-arrays, specifically 

`In rare cases, you may have already added a separate Variable for “Coke”, one for “Pepsi”, and one for “RC”. You may move them to a single array variable by POSTing a Variable Entity for the array that instead of a “subreferences” attribute has a “subvariables” attribute, a list of URL’s of the variables you’d like to bind together:`

I build the payload:
```python
{
    "entity": "shoji:entity",
    "body": {
        "name": "test_create_cat_array",
        "type": "categorical_array",
        "subvariables": [
            "https://alpha.crunch.io/api/datasets/9825ab3f23f4460288f6f74b6512f3e2/variables/000016/",
            "https://alpha.crunch.io/api/datasets/9825ab3f23f4460288f6f74b6512f3e2/variables/000018/"
        ]
    }
}
```

This will fail with some strange error:
pycrunch.lemonpy.ClientError: (<Response [400]>, 'https://alpha.crunch.io/api/datasets/9825ab3f23f4460288f6f74b6512f3e2/variables/', {'status': '400 Bad Request', 'message': "Problem with input: Column '000018' length 0 does not match existing length 1."})
