### ISSUE TITLE
Expose 'Organize filters' control

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#192]
When you're the current editor of a dataset, an 'Organize' option becomes available from the 'Filters' drop-down. This lets you drag/drop to reorder the filters.

We would want something like:

```python
ds.filters.organize(filter_list)
```

Where `filter_list` was a list of all the available filters to be reordered (from the top) either as string names or filter objects. Perhaps unmentioned filters automatically bump to the end?

**Comment by jamesrkg** [comment]
When you tackle this please remember that some of the filters may not be set to public.

**Comment by xbito** [comment]
@jjdelc What do you think should be the API for this in scrunch?

**Comment by jjdelc** [comment]
This in the API is a list of filter URLs. 

How would you get a hold of that `filter_list` and what would be inside if? String IDs? Or Filter objects?

The rules for this filter list would be the same that the `/dataset/id/filters/flat/` endpoint has regarding what it accepts or not. Each user has their own list of filters that can be accepted.

Also, maybe we should use `reorder` since it's a terminology used for reordering other things?

**Comment by jamesrkg** [comment]
@jjdelc for Automation.
