### ISSUE TITLE
Support for headings and subtotals

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#235]
I don't have an API documentation reference for this (not sure there is one?) but the rcrunch reference can be seen here:

https://github.com/Crunch-io/rcrunch/blob/master/R/subtotals-and-headings.R

**Comment by xbito** [comment]
We are in the process of finding out how that is done in R, is it API calls and the work is done in Crunch, or is the work done in R? Or a combination?

**Comment by jamesrkg** [comment]
More references:

https://github.com/Crunch-io/ta-da/pull/18/files

http://docs.crunch.io/feature-guide/feature-analyzing.html#insertions

Insertions are a subtype of transform: a declarative list of second-order computations or other things to do with `crunch:cube`-shaped results.

https://github.com/Crunch-io/rcrunch/blob/501f475434381512a7b2d1ff897a776d0d5cf668/vignettes/subtotals.Rmd

There is also (maybe not evident here) a special "top" and "bottom" rather than category anchor.

**Comment by jonkeane** [comment]
To answer some of the questions from @xbito above:

Yes, subtotals and headers are two types of insertions (which as you note @jamesrkg, are stored in the transform metadata on variables). These insertions are designed to be calculated and inserted by clients when they display the results from CrunchCubes. The transform metadata for each variable is included in the CrunchCube response for this purpose.

There are two main tasks with subtotals: (1) setting them on variables and (2) calculating and displaying them in CrunchCubes.

For (1) setting them on variables: you need to issue a `PATCH` to a variable's url with a payload that's looks like:
```
{
  "view": {
    "transform": {
      "insertions": [
        {
          "anchor": 2,
          "name": "a fancy, new subtotal of category 1 and 2",
          "function": "subtotal",
          "args": [1, 2]
        }
      ]
    }
  }
}
```
This would specify a subtotal of category ids 1 and 2 to be anchored to follow category 2 when it is displayed. 

For (2) calculating and displaying them: because CrunchCubes include both the counts (or other measures) for each category as well as the metadata for the insertions, the client working with the cube is responsible for calculating the subtotals and inserting them into the CrunchCube display. 
You might be interested in [the open source python package](https://github.com/Crunch-io/crunch-cube) we are working on. It's designed to work with and display CrunchCube responses (including calculating and displaying the transforms). It is not fully complete yet, but is in active development. Otherwise, if you want to implement this in scrunch internally, you can read the insertions from transform metadata and then calculate the subtotals based on summing the counts for the appropriate cells in the cube.

Let me know if I can be of any help explaining how insertions are intended to work or how we implemented them in rcrunch.
