### ISSUE TITLE
Time taken to get_project seems to scale with the number of datasets in a project

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#246]
`get_project` is very fast if the project being targeted doesn't have many datasets in it, but when the number of datasets in the project is very large it takes a lot longer. This suggests that the speed of `get_project` scales with the number of datasets in the targeted project. It's not clear yet which of scrunch or pycrunch plays the pivotal role in this behavior so this ticket is partly to explore that. If not scrunch we can ticket for pycrunch instead.

**Comment by mathiasbc** [comment]
@jamesrkg: Fixed in: https://github.com/Crunch-io/scrunch/commit/005b824ffca2c19d5447dca186da815fd982013b.

The culprit for resource expensive instantiation of the class Project is the attribute order. It is now solved by making order a lazy attribute, which means that when calling project.order the delay will be there but not on Project instantiation
