### ISSUE TITLE
ds.replace_from_csv

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#288]
The idea here is as-per `replace_values` except that a CSV is consumed containing a column of ids paired to the dataset and 1+ additional columns headed by sub/varaible aliases. The method would then match on the ids to overwrite those columns with this indicated data.

For example, given the CSV:

```
id	gen	age	reg
43	1	38	8
31	1	22	2
41	2	42	5
82	1	25	5
26	2	19	3
92	2	29	4
62	1	51	9
```

Something like:

```
ds.replace_from_csv(match_on='id', data=path_csv, sep=',')
```

Resulting in all of the data from the CSV overwriting whatever data was in those variables, for those ids.

@jjdelc can you suggest the best approach for tackling this one using the fewest possible hits against the API. Could it be reduced to 1 call per id? 1 per variable? Can the API take all of this in one go? If 1 call per id per variable is required then internally this could rely on `var.replace_values`, each time filtering on the id.

I've framed this as `replace_from_csv` but it could also be `replace_from_dataframe` (didn't realize initially that pandas is already a dependency).

**Comment by jjdelc** [comment]
The CSV part of this command would definitely need to be handled in scrunch, since the only way we accept CSVs on the API is to add new rows. So sending it straight to the API right now is not possible.

Once we have that CSV translated to python values, then it'll be a matter to do the updates using the `/table/` endpoint to perform update commands.

you could POST something like this:
```
{
            "command": "update",
            "variables": {
                # Here for each variable you send a `column` with the list of values (col) from the csv
                age_var: {"column": [1, 1, {'?': -1}]},
                reg_var: {"column": [100, 200, 300]},
            },
            "filter": # Filter column ID "in" the given values
        }
```

**Comment by jamesrkg** [comment]
Thanks @jjdelc , so 1 POST per id. 👍

**Comment by jjdelc** [comment]
It should be possible to do it all at once, IFF you can rely on the order of your filter and the way rows are stored currently in the dataset. In the `filter` section of the command you would do a function `"id" in [1, 3, 100, 5]` and then you will replace that resulting subset with your new column of values ``[4, 5, 6, 7]`  but will have to be careful since at no point there is a way to say "but ordered by ID ascending" it will be by the order of what the rows are in, which may not be the same order of your CSV.

**Comment by jjdelc** [comment]
safestest way is 1 update per row, then you don't have to worry about order

**Comment by jamesrkg** [comment]
Yep, I think for paranoia's sake we'd want to do 1 hit per row. There's a blindness to the edit otherwise that would be quite risky. Still, from the scrunch user's point of view we're looking at 1 step which is the key advantage over `replace_values` in a situation like this.

**Comment by nealrichardson** [comment]
Please don't do one update per row. Crunch is column-major, so please send column by column.

**Comment by xbito** [comment]
Doing a replace_values column by column even with a filter is going to be a pain, we don't know in what order the results are going to come back (we could filter the id column frist, then order the other columns respecting that?).
But there is another way, we could use the stream to receive this kind of data. We would have to do the transformation from CSV to the LDJSON format, but other than that it should be straightforward. Things to look out:
- What if the dataset doesn't have the streaming flag set? We should temporarily set it to streaming. And at the end return it back to the previous state.
- What if the dataset has no primary key set? We should try to set it to the identifier used in the call and unset it at the end?
- What if the dataset has a different primary key? We should return an error and ask the user to use that as the identifier.
- "The end" should be sending doing and waiting for a batch operation to complete after sending all of the rows.

**Comment by mathiasbc** [comment]
@jamesrkg https://github.com/Crunch-io/scrunch/pull/338

**Comment by jamesrkg** [comment]
Thanks @mathiasbc I'll check this out as soon as I can.
