### ISSUE TITLE
derive_weight enhancements

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#332]
Now that we have `derive_weight` (#324) we need to look at some enhancements for the initial implementation. 

It's not clear to me how much of this is implemented on the Crunch side. @jjdelc we'll need your input to clarify what is/isn't currently possible (hence initial assignment of this ticket). I'm not sure if any of it is currently supported. If that is the case we'll have to leave this in the back log and I will email support instead.

I've take these enhancements from the original ticket (#57).

1. Multiple source weight lists/variables via a list of dict given to `targets`:

```
ds.derive_weight(
    targets=[
        {'gender' : {
            1: .45, 
            2: .55}},
        {'locality': {
            1: .10, 
            2: .15, 
            3: .20, 
            4: .25, 
            5: .30}}
    ],
    alias='age-weight-test',
    name='age-weight-test'
)
```

2. Applying weights only to a subgroup via `filter`

```
ds.derive_weight(
    filter='wave == 1',
    targets=[
        {'gender' : {
            1: .45, 
            2: .55}},
        {'locality': {
            1: .10, 
            2: .15, 
            3: .20, 
            4: .25, 
            5: .30}}
    ],
    alias='age-weight-test',
    name='age-weight-test'
)
```

3. Control the total weighted base via 'total' (rename as preferred!):

```
ds.derive_weight(
    total=10000,
    targets=[
        {'gender' : {
            1: .45, 
            2: .55}},
        {'locality': {
            1: .10, 
            2: .15, 
            3: .20, 
            4: .25, 
            5: .30}}
    ],
    alias='age-weight-test',
    name='age-weight-test'
)
```

In this example the total weighted base would appear to be 10,000.

**Comment by jjdelc** [comment]
The first request, about including multiple variables with different targets is possible, here's a pycrunch example:
```
varcat = ds.variables.by('alias')
targets = [{
    'variable': varcat['var0'].entity_url,
    'targets': [[1, 0.4], [2, 0.6]]
}, {
    'variable': varcat['var1'].entity_url,
    'targets': [[1, 0.3], [2, 0.4], [3, 0.3]]
}]
request = {
    'expr': {'function': 'rake', 'args': targets},
    'name': 'weight',
    'description': 'this is lightweight'
}
ds.variables.create(as_entity(request))
wt = ds.variables.by('name')['weight'].entity

self.assertEqual(wt.body.type, 'numeric')
self.assertEqual(wt.body.name, 'weight')
self.assertEqual(wt.body.description, 'this is lightweight')
self.assertEqual(wt.body.derivation['args'], [{
    'variable': varcat['var0'].entity_url.relative_to(wt.self),
    'targets': [[1, 0.4], [2, 0.6]]
}, {
    'variable': varcat['var1'].entity_url.relative_to(wt.self),
    'targets': [[1, 0.3], [2, 0.4], [3, 0.3]]
}])
```

The 2nd request, is not really possible on the backend, all values need a weight, in such case Scrunch would need to backfill everything filtered out with weight 0. Since the weight variable applies to all the rows in the unfiltered dataset. The problem will be on matching the capricious filter with categories to apply weights on. You'd first need to create a case variable with that arbitrary filter and then somehow apply the weights on the rest of categories outside of that result of rows... that would all need to be calculated by the client. But the behavior is not something we support, and even less guaranteed across other clients (these variables wouldn't be immediately obviois in the web app) 

The 3rd request is not completely clear to me. When sending the targets, the backend will validate that they add up to 100%. If you want other validation, then it would need to be made by Scrunch, get a summary of coutns per category and multiply per target and count the result, but in the case of multiple targets, things become extremely hairy to re-implement rake calculations on the client.

**Comment by jamesrkg** [comment]
Thanks @jjdelc . 

Good to see the 1st request is supported. This will cover most use cases. @xbito do you want me to ticket that separately given there are some parts of this issue now that can't be done?

2nd request not being possible - I can see how that would be the case. Is there a more natural Crunch way to achieve the end result of having a single weight variable containing weights that have been generated independently? E.g. weights calculated per-country in a multi-country study (these may not even rely on the same variables for their weights, so interlocking is not an option).

3rd request is not very common so if this isn't possible it's not a huge problem. What I mean is if you captured 2000 respondents for a study, typically the weighted base will also be 2000 (when the average weight factor is 1). Occasionally a client will instead want the total weighted base to be equal to the actual population described by weight profile. For example if weighted to Australia's Nat Rep profile the client may wish to see the total weighted base as 24.6m. Only the weighted counts are affected in this case, weighted percentages remain the same.

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/336

**Comment by jamesrkg** [comment]
Thanks @mathiasbc
