### ISSUE TITLE
Expression parser - not_selected

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/scrunch#334]
Crunch logic has evolved from binary (True/False) to ternary, also called 3-value-logic or 3VL (Selected/Other/Missing). Details of this can be found here:

https://docs.crunch.io/feature-guide/feature-deriving.html?highlight=logic#categorical-logic

The Crunch API was updated such that all existing operators behave in the now-native 3VL manner. 

# 1.

The behavior of `not` has changed from 2VL to 3VL, and `not_selected` has been added to support the old 2VL-style expression. Therefore:

#### i.

Add support for `not_selected` to the expression parser. In theory this should be usable anywhere that `not` is usable. For example:

`not A in [1, 2, 3]`
`not_selected A in [1, 2, 3]`

#### ii.

Add new shorthand notation for `not_selected` as `!#`. This would compliment the existing behavior such that:

`A != B` is to `not(A == B)`
as
`A !# B` is to `not_selected(A == B)`

# 2. 

After the above, we need to correct the scrunch documentation regarding expression logic and also provide users with guidance if binary-style logic is still required. I'll do this part.

**Comment by mathiasbc** [comment]
The functions and syntax of Crunch API has been getting bigger. The current parser we have relies on the Python AST to traverse nodes and build the appropriate JSON. But cases like this are not gonna be supported in the AST module simply because something like `not_selected A` is not valid Python syntax.

There is a workaround for this which is to use function calls, which our parser currently supports, so `not_selected A in [1,2,3]` would need to be declared as `not_selected(Q9b in [1,2,3])` which is the correct syntax for `not` as well; `not(A in [1,2,3])`.

Given this limitation we are not gonna be able to implement the `!#` operator as the current state of the parser. 

I can only think of forking the Python AST and add classes for these special kind of syntax we are going to need (not really a great idea) or we could offer interfaces to them as functions supported with well written documentation.

**Comment by jamesrkg** [comment]
@mathiasbc this would be fine.
