### ISSUE TITLE
Provide a means to iterate over the Dataset's variables

### ISSUE THREAD

**Issue by alejandro-rivera** [Crunch-io/scrunch#48]
It would be nice having a `variables()` method in the `Dataset` class that would return an _iterator_ over the Dataset's variables. It would like like so:

```python
for var in dataset.variables():
    print(var)
```

This method could also allow some filtering on the variables that would be iterated. For example:

```python
for hidden_var in dataset.variables(discarded=True):
    print(hidden_var)
```

Note: this has been requested by an early adopter of the scrunch library.

**Comment by jjdelc** [comment]
We already expose a half implementation of the dict protocol on the dataset on `__getitem__`. What would be the downsides to implementing the rest of methods there? `__iter__`, `keys`, `iterkeys`, `items`, iteritems`, `values`, `itervalues`. These would return the public variables under `/variables/` unordered (since the variable order is not flat)

I would let the inspection on the user to python what they  want and what not, the combinations of parameters will need us having to make decisions that may not be fit for everyone when they can just add an `if condition` when they need in their loops.

**Comment by xbito** [comment]
While we are at it we should also do __contains__, maybe __len__ too?

**Comment by mathiasbc** [comment]
https://github.com/Crunch-io/scrunch/pull/61
